### ISSUE TITLE
任何报错都npm install xxx就行了，解出来可以用，资源也完好

### ISSUE THREAD

**Issue by Skierhou** [superBiuBiuMan/wechatMiniAppReverse#2]
如：Error: Cannot find module 'cheerio'
npm install cheerio

**Comment by toubio** [comment]
at makeNiceSyntaxError (D:\wx\wechatMiniAppReverse-main\2.second\nodejs\node_modules\vm2\lib\transformer.js:41:16)
    at transformer (D:\wx\wechatMiniAppReverse-main\2.second\nodejs\node_modules\vm2\lib\transformer.js:84:8)
    at VM.run (D:\wx\wechatMiniAppReverse-main\2.second\nodejs\node_modules\vm2\lib\vm.js:491:16)
    at z (D:\wx\wechatMiniAppReverse-main\2.second\nodejs\wuWxml.js:366:7)
    at z (D:\wx\wechatMiniAppReverse-main\2.second\nodejs\wuRestoreZ.js:244:17)
    at catchZGroup (D:\wx\wechatMiniAppReverse-main\2.second\nodejs\wuRestoreZ.js:15:2)
    at catchZ (D:\wx\wechatMiniAppReverse-main\2.second\nodejs\wuRestoreZ.js:19:29)
    at getZ (D:\wx\wechatMiniAppReverse-main\2.second\nodejs\wuRestoreZ.js:244:2)
    at wu.get.code (D:\wx\wechatMiniAppReverse-main\2.second\nodejs\wuWxml.js:354:3)
    at ioLimit.runWithCb (D:\wx\wechatMiniAppReverse-main\2.second\nodejs\wuLib.js:80:8)

**Comment by yanqibin** [comment]
# 安装兼容老 Node.js 的版本 
 


npm install esprima@4.0.1 -g
npm install css-tree@1.1.3 -g
npm install cssbeautify@0.3.1 -g
npm install vm2@3.9.17 -g
npm install uglify-es@3.3.9 -g
npm install js-beautify@1.14.0 -g
npm install escodegen@2.0.0 -g
npm install cheerio@0.22.0 -g
