### ISSUE TITLE
大神，解包过程中报错，已经按规范格式书写Issue

### ISSUE THREAD

**Issue by cfx666** [superBiuBiuMan/wechatMiniAppReverse#4]
程序执行命令:node .\wuWxapkg.js D:\某团优选\ 解密后\\__APP__解密.wxapkg

程序执行错误信息:
SyntaxError: Unexpected token '}'
    at makeNiceSyntaxError (C:\Users\xy\node_modules\vm2\lib\transformer.js:41:16)
    at transformer (C:\Users\xy\node_modules\vm2\lib\transformer.js:84:8)
    at VM.run (C:\Users\xy\node_modules\vm2\lib\vm.js:491:16)
    at z (C:\Users\xy\Desktop\wechatMiniAppReverse-main\wechatMiniAppReverse-main\2.second\nodejs\wuWxml.js:366:7)
    at z (C:\Users\xy\Desktop\wechatMiniAppReverse-main\wechatMiniAppReverse-main\2.second\nodejs\wuRestoreZ.js:244:17)
    at catchZGroup (C:\Users\xy\Desktop\wechatMiniAppReverse-main\wechatMiniAppReverse-main\2.second\nodejs\wuRestoreZ.js:15:2)
    at catchZ (C:\Users\xy\Desktop\wechatMiniAppReverse-main\wechatMiniAppReverse-main\2.second\nodejs\wuRestoreZ.js:19:29)
    at getZ (C:\Users\xy\Desktop\wechatMiniAppReverse-main\wechatMiniAppReverse-main\2.second\nodejs\wuRestoreZ.js:244:2)
    at wu.get.code (C:\Users\xy\Desktop\wechatMiniAppReverse-main\wechatMiniAppReverse-main\2.second\nodejs\wuWxml.js:354:3)
    at ioLimit.runWithCb (C:\Users\xy\Desktop\wechatMiniAppReverse-main\wechatMiniAppReverse-main\2.second\nodejs\wuLib.js:80:8)

程序结果错误信息：某团优选小程序，第一步解密成功了，第二步解包出错了
第一步：pc_wxapkg_decrypt.exe -wxid wx77af438b3505c00e -in D:\某团优选\\\__APP__.wxapkg  -out D:\某团优选\解密后\\__APP__解密.wxapkg
![image](https://user-images.githubusercontent.com/77578079/192134346-36be8fc8-504c-4f12-b9d9-a3c4ff77c8e4.png)
第二步：执行node .\wuWxapkg.js D:\某团优选\ 解密后\\__APP__解密.wxapkg命令之后报错，试了好几次都是相同的错误，跪求指教
![image](https://user-images.githubusercontent.com/77578079/192134548-9604ab98-bc1e-4b07-af98-604f547df41a.png)

程序包:
[程序包.zip](https://github.com/superBiuBiuMan/wechatMiniAppReverse/files/9640289/default.zip)

其他附加内容:上传的程序包总共二个，\__APP__.wxapkg是未解密的包，__APP__解密.wxapkg是解密后的包

**Comment by cfx666** [comment]
程序执行命令:node .\wuWxapkg.js D:\某团优选\ 解密后\__APP__解密.wxapkg

程序执行错误信息：
![image](https://user-images.githubusercontent.com/77578079/192134548-9604ab98-bc1e-4b07-af98-604f547df41a.png)
SyntaxError: Unexpected token '}'
    at makeNiceSyntaxError (C:\Users\xy\node_modules\vm2\lib\transformer.js:41:16)
    at transformer (C:\Users\xy\node_modules\vm2\lib\transformer.js:84:8)
    at VM.run (C:\Users\xy\node_modules\vm2\lib\vm.js:491:16)
    at z (C:\Users\xy\Desktop\wechatMiniAppReverse-main\wechatMiniAppReverse-main\2.second\nodejs\wuWxml.js:366:7)
    at z (C:\Users\xy\Desktop\wechatMiniAppReverse-main\wechatMiniAppReverse-main\2.second\nodejs\wuRestoreZ.js:244:17)
    at catchZGroup (C:\Users\xy\Desktop\wechatMiniAppReverse-main\wechatMiniAppReverse-main\2.second\nodejs\wuRestoreZ.js:15:2)
    at catchZ (C:\Users\xy\Desktop\wechatMiniAppReverse-main\wechatMiniAppReverse-main\2.second\nodejs\wuRestoreZ.js:19:29)
    at getZ (C:\Users\xy\Desktop\wechatMiniAppReverse-main\wechatMiniAppReverse-main\2.second\nodejs\wuRestoreZ.js:244:2)
    at wu.get.code (C:\Users\xy\Desktop\wechatMiniAppReverse-main\wechatMiniAppReverse-main\2.second\nodejs\wuWxml.js:354:3)
    at ioLimit.runWithCb (C:\Users\xy\Desktop\wechatMiniAppReverse-main\wechatMiniAppReverse-main\2.second\nodejs\wuLib.js:80:8)

程序结果错误信息：某团优选小程序，第一步解密成功了，第二步解包出错了
第一步：pc_wxapkg_decrypt.exe -wxid wx77af438b3505c00e -in D:\某团优选\__APP__.wxapkg  -out D:\某团优选\解密后\__APP__解密.wxapkg
![image](https://user-images.githubusercontent.com/77578079/192134346-36be8fc8-504c-4f12-b9d9-a3c4ff77c8e4.png)
第二步：执行node .\wuWxapkg.js D:\某团优选\ 解密后\__APP__解密.wxapkg命令之后报错，试了好几次都是相同的错误，跪求指教

程序包:
[程序包.zip](https://github.com/superBiuBiuMan/wechatMiniAppReverse/files/9640289/default.zip)

其他附加内容:上传的程序包总共二个，__APP__.wxapkg是未解密前的包，__APP__解密.wxapkg是解密后的包

**Comment by andyge2014** [comment]
我也是到了“SyntaxError: Unexpected token '}'”这一步，没有拿到wxml 和 wxss文件。好像是小程序官方升级了

**Comment by Mrfuture1** [comment]
同遇到这个问题，有解吗？

**Comment by guochen2** [comment]
> 我也是到了“SyntaxError: Unexpected token '}'”这一步，没有拿到wxml 和 wxss文件。好像是小程序官方升级了

同样 我也是这个问题
